# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 15:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='业务线名称', max_length=32, verbose_name='业务线名称')),
                ('pid', models.IntegerField(db_index=True, help_text='上级业务线id', verbose_name='上级业务线id')),
                ('module_letter', models.CharField(help_text='业务线字母简称', max_length=32, verbose_name='业务线字母简称')),
                ('dev_interface', models.ManyToManyField(help_text='开发接口人', related_name='dev_interface', to=settings.AUTH_USER_MODEL, verbose_name='开发接口人')),
                ('op_interface', models.ManyToManyField(help_text='运维接口人', related_name='op_interface', to=settings.AUTH_USER_MODEL, verbose_name='运维接口人')),
            ],
            options={
                'db_table': 'resources_product',
                'ordering': ['id'],
                'permissions': (('view_product', 'can view products'),),
            },
        ),
    ]
