# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='/', help_text='目录名或文件名', max_length=100, verbose_name='目录名或文件名')),
                ('icon', models.CharField(help_text='图标名', max_length=32, null=True, verbose_name='图标名')),
                ('title', models.CharField(help_text='路由显示名', max_length=255, verbose_name='路由显示名')),
                ('show', models.BooleanField(default=False, help_text='该路由是否显示', verbose_name='该路由是否显示')),
                ('groups', models.ManyToManyField(blank=True, help_text='所属组', related_name='menu_set', related_query_name='menu', to='auth.Group', verbose_name='groups')),
                ('parent', models.ForeignKey(help_text='上级菜单', null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Menu', verbose_name='上级菜单')),
            ],
            options={
                'db_table': 'view_menu',
                'ordering': ['title'],
            },
        ),
    ]
