# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(help_text='idc字母简称', max_length=10, unique=True, verbose_name='idc字母简称')),
                ('name', models.CharField(help_text='idc名称', max_length=30, verbose_name='idc名称')),
                ('address', models.CharField(blank=True, help_text='idc具体地址', max_length=255, null=True, verbose_name='idc具体地址')),
                ('tel', models.CharField(blank=True, help_text='客服电话', max_length=15, null=True, verbose_name='客服电话')),
                ('mail', models.EmailField(blank=True, help_text='联系人邮箱', max_length=255, null=True, verbose_name='联系人邮箱')),
                ('remark', models.CharField(blank=True, help_text='备注说明', max_length=255, null=True, verbose_name='备注说明')),
            ],
            options={
                'db_table': 'resources_idc',
                'ordering': ['id'],
                'permissions': (('view_idc', 'cat view idc'),),
            },
        ),
    ]
