# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlmng', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbconf',
            options={'permissions': (('view_dbconf', 'cat view dbconf'),)},
        ),
        migrations.AlterModelOptions(
            name='inceptsql',
            options={'permissions': (('view_inceptsql', 'cat view inceptsql'),)},
        ),
    ]
