# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabinet', '0001_initial'),
        ('products', '0001_initial'),
        ('idcs', '0001_initial'),
        ('manufacturers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(db_index=True, max_length=20, verbose_name='ip地址')),
                ('netmask', models.CharField(max_length=20, verbose_name='子网掩码')),
            ],
            options={
                'db_table': 'resources_ip',
                'permissions': (('view_ip', 'cat view ip'),),
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='网卡设备名')),
                ('mac', models.CharField(max_length=32, verbose_name='网卡mac地址')),
                ('remark', models.CharField(max_length=300, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'resources_networkdevice',
                'permissions': (('view_networkdevice', 'cat view networkdevice'),),
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture_data', models.DateField(help_text='制造日期', null=True, verbose_name='制造日期')),
                ('cabinet_position', models.CharField(help_text='机柜内位置', max_length=32, null=True, verbose_name='机柜内位置')),
                ('warranty_time', models.DateField(help_text='保修时间', null=True, verbose_name='保修时间')),
                ('purchasing_time', models.DateField(help_text='采购时间', null=True, verbose_name='采购时间')),
                ('power_supply', models.IntegerField(help_text='电源功率', null=True, verbose_name='电源功率')),
                ('os', models.CharField(default=None, help_text='操作系统', max_length=100, verbose_name='操作系统')),
                ('hostname', models.CharField(db_index=True, default=None, help_text='主机名', max_length=50, verbose_name='主机名')),
                ('manage_ip', models.CharField(db_index=True, default=None, help_text='管理IP', max_length=32, verbose_name='管理IP')),
                ('server_cpu', models.CharField(default=None, help_text='CPU信息', max_length=250, verbose_name='CPU信息')),
                ('disk', models.CharField(help_text='硬盘信息', max_length=300, null=True, verbose_name='硬盘信息')),
                ('server_mem', models.CharField(default=None, help_text='内存信息', max_length=100, verbose_name='内存信息')),
                ('status', models.CharField(db_index=True, help_text='服务器状态', max_length=32, null=True, verbose_name='服务器状态')),
                ('remark', models.TextField(help_text='备注', null=True, verbose_name='备注')),
                ('last_check', models.DateTimeField(auto_now=True, help_text='上次检测时间', verbose_name='上次检测时间')),
                ('uuid', models.CharField(db_index=True, help_text='UUID', max_length=100, null=True, unique=True, verbose_name='UUID')),
                ('sn', models.CharField(db_index=True, help_text='SN', max_length=40, null=True, verbose_name='SN')),
                ('rmt_card_ip', models.CharField(help_text='远程管理卡IP', max_length=15, null=True, verbose_name='远程管理卡IP')),
                ('server_type', models.IntegerField(db_index=True, default=0, help_text='机器类型', verbose_name='机器类型')),
                ('cabinet', models.ForeignKey(help_text='所在机柜', null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.Cabinet', verbose_name='所在机柜')),
                ('idc', models.ForeignKey(help_text='所在机房', null=True, on_delete=django.db.models.deletion.CASCADE, to='idcs.Idc', verbose_name='所在机房')),
                ('manufacturer', models.ForeignKey(help_text='制造商', null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturers.Manufacturer', verbose_name='制造商')),
                ('model_name', models.ForeignKey(default=None, help_text='服务器型号', on_delete=django.db.models.deletion.CASCADE, to='manufacturers.ProductModel', verbose_name='服务器型号')),
                ('server_purpose', models.ForeignKey(help_text='二级产品线', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_purpose', to='products.Product', verbose_name='二级产品线')),
                ('service', models.ForeignKey(help_text='一级业务线', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='products.Product', verbose_name='一级业务线')),
            ],
            options={
                'db_table': 'resources_server',
                'permissions': (('view_server', 'cat view server'),),
            },
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Server', verbose_name='所在服务器'),
        ),
        migrations.AddField(
            model_name='ip',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.NetworkDevice', verbose_name='网卡'),
        ),
    ]
