# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180817_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
